name: Build Cross-Platform

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install --no-audit --no-fund
    
    - name: Install submodule dependencies (frontend)
      run: |
        if [ -d "frontend" ]; then
          cd frontend && npm install --legacy-peer-deps
        fi
      shell: bash
    
    - name: Install submodule dependencies (server-node)  
      run: |
        if [ -d "server-node" ]; then
          cd server-node && npm install --legacy-peer-deps  
        fi
      shell: bash
    
    - name: Build frontend
      run: |
        if [ -d "frontend" ]; then
          cd frontend && npm run build
        fi
      shell: bash
    
    - name: Build Electron app
      run: npm run electron:build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_OPTIONS: --max-old-space-size=4096
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ matrix.os }}
        path: |
          release/*.exe
          release/*.dmg
          release/*.AppImage
          release/*.deb 